opt_in_rules:
  - first_where
  - last_where
  - private_swiftui_state
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

disabled_rules:
  - identifier_name
  - trailing_whitespace
  - force_cast
  - force_try
  - function_body_length
  - todo

line_length:
  warning: 180
  error: 240
  ignores_comments: true

included:
  - iOSEngineerCodeCheck

excluded:
